@startuml
left to right direction
package leavemanagement {
    rectangle leaveapplication {
        usecase "create leave application" as uc1
        usecase "view leave application" as uc9
    }
    rectangle leaverequest {
        usecase "consider leave request" as uc2
        usecase "export leave request" as uc3
    }
    rectangle report {
        usecase "view personal leave statistic " as uc4
        usecase "view user's leave statistic" as uc8
        usecase "view leave history" as uc5
    }
    rectangle heatmap {
        usecase "view heatemap" as uc6
    }
    rectangle overview {
        usecase "view calendar" as uc7
        usecase "view leave type analyst" as uc10
    }
}
rectangle Authority {
    actor Admin 
    actor Supervisor
    actor HR
}
actor User 
HR --- uc1
Supervisor --- uc1
uc1 --- User 

Authority --- uc2
HR --- uc3
Admin --- uc3

Authority -- uc7
uc4 ---- User
HR --- uc4
Supervisor --- uc4

Admin --- uc8
HR --- uc8

HR --- uc9
Supervisor --- uc9
User --- uc9

Authority -- uc6

uc5 --- User
HR --- uc5
Supervisor --- uc5

HR --- uc10
Admin --- uc10
@enduml 